//Config
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import { configApp } from "../../config/configApp";
//Components
import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>{configApp.nameApp}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientOnly>
        <Header/>
        <div>oorueba</div>
        <Footer/>
      </ClientOnly>
    </>
  );
}
