//Components
import Head from 'next/head'
import { Inter } from 'next/font/google'
import ClientOnly from '@/src/components/ClientOnly/ClientOnly'
import Header from '@/src/components/Header/Header'
import Footer from '@/src/components/Footer/Footer'
//Config
import {configApp} from '../config/configApp'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{configApp.nameApp}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientOnly>
        <Header/>
        <Footer/>
      </ClientOnly>
    </>
  )
}
