//Components
import Head from 'next/head'
import { Inter } from 'next/font/google'
import ClientOnly from '@/src/components/ClientOnly/ClientOnly'
import Header from '@/src/components/Header/Header'
import Footer from '@/src/components/Footer/Footer'
import Frases from '@/src/components/Frases/Frases'
import Carrousel from '@/src/components/Carrousel/Carrousel'
import Banners from '@/src/components/Banners/Banners'
import Condiciones from '@/src/components/Condiciones/Condiciones'
import Contacto from '@/src/components/Contacto/Contacto'
//Config
import {configApp} from '../config/configApp'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>{configApp.nameApp}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ClientOnly>
        <Header/>
        <Frases/>
        <Carrousel/>
        <Frases/>
        <Banners/>
        <Contacto/>
        <Condiciones/>
        <Footer/>
      </ClientOnly>
    </>
  )
}
